### ISSUE TITLE
Folder structuring

### ISSUE THREAD

**Issue by LukeSamkharadze** [tancredi/fantasticon#177]
I want to restructure my folder

**From:**
![image](https://user-images.githubusercontent.com/31849767/116248923-57293100-a77d-11eb-9153-0966850c2cb4.png)
**To:**
![image](https://user-images.githubusercontent.com/31849767/116248748-2a751980-a77d-11eb-9b3b-5f49ff45f545.png)

And still get the same `CSS` generated, currently `.svg` is not generated as `.icons-check`)

``` CSS
.icons-check:before {
    content: "\f105";
}
.icons-check-circle:before {
    content: "\f106";
}
```

I think this feature would be neat (Instead of `.svg` we could have used `_.svg` or something)
